name: PensionSimulator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - ipyvuetify
  - ipywidgets
  - traitlets==4.3.3
  - numpy
  - pandas
  - plotly
  - blinker
  - python-dateutil
  - ipython
  - jupyterlab>=3.1
  - voila>=0.2.11
  - marshmallow
  - pip:
      - marshmallow_dataclass
      - marshmallow_enum