name: PensionSimulator
channels:
  - conda-forge
  - defaults
dependencies:
  - ipyvuetify
  - ipywidgets
  - traitlets
  - plotly
  - pandas
  - blinker
  - numpy
  - python-dateutil
  - ipython
  - jupyterlab>=3.1
  - voila>=0.2.11